[workspace]
members = [
    "stabilitypool-common",
    "stabilitypool-client",
]
resolver = "2"

[patch.crates-io]
secp256k1-zkp = { git = "https://github.com/dpc/rust-secp256k1-zkp/", branch = "sanket-pr" }
